"use client";

import { paiseExact, rupees } from "@/lib/format";
import type { TheatreEvent } from "@/lib/types";

/**
 * Dwaar, read as an instrument.
 *
 * The top half is the whole product in two numbers: what the agent said the
 * total was, and what the gate computed it to be. When they agree the second
 * one is the only one that ever mattered. When they disagree, the difference is
 * the reason nothing moved.
 *
 * The bottom half is the evidence -- every rule that was evaluated, with the
 * observed value and the limit it was tested against, in paise. No rule text is
 * generated by a model; these are deterministic templates.
 */

export function DwaarPanel({
  verdict,
}: {
  verdict: Extract<TheatreEvent, { type: "verdict" }> | null;
}) {
  const computed = verdict?.computed_paise;
  const quoted = verdict?.quoted_paise;
  const drifted =
    verdict !== null && computed !== undefined && quoted !== computed;
  const denied = verdict?.outcome === "DENY";

  const accent = denied
    ? "text-vermilion"
    : verdict === null
      ? "text-paper-faint"
      : "text-brass";

  return (
    <section className="panel flex min-h-0 flex-col">
      <div className="panel-head flex items-baseline justify-between px-4 py-3">
        <h2 className="font-mono text-[13px] font-semibold uppercase tracking-[0.18em] text-paper">
          Dwaar
          <span className="deva ml-2 text-[15px] font-normal text-paper-dim">
            द्वार
          </span>
        </h2>
        <span className="eyebrow">the gate</span>
      </div>

      {/* The signature reading: two figures, one of which is the truth. */}
      <div className="border-b border-rule px-4 py-4">
        <div className="grid grid-cols-2 gap-px bg-rule">
          <div className="bg-ink-raised px-3 py-3">
            <span className="eyebrow">Agent quoted</span>
            <p
              className={`figures mt-1.5 text-[19px] ${
                drifted
                  ? "text-vermilion line-through decoration-vermilion/60"
                  : "text-paper-dim"
              }`}
            >
              {quoted === undefined ? "—" : rupees(quoted)}
            </p>
            <p className="mt-0.5 text-[10px] text-paper-faint">
              discarded, always
            </p>
          </div>

          <div className="bg-ink-raised px-3 py-3">
            <span className="eyebrow">Dwaar computed</span>
            <p className={`figures mt-1.5 text-[19px] ${accent}`}>
              {computed === undefined ? "—" : rupees(computed)}
            </p>
            <p className="mt-0.5 text-[10px] text-paper-faint">
              {computed === undefined
                ? "no cart was priced"
                : "from signed catalogue lines"}
            </p>
          </div>
        </div>

        {verdict === null ? (
          <p className="mt-3 text-[12px] text-paper-faint">
            No proposal has reached the gate yet.
          </p>
        ) : drifted ? (
          <p className="mt-3 border border-vermilion-dim bg-vermilion/10 px-3 py-2 text-[12px] text-vermilion">
            Drift of {paiseExact(Math.abs((quoted ?? 0) - (computed ?? 0)))}.
            The size of the gap does not matter — any gap is a hard denial.
          </p>
        ) : computed === undefined ? (
          <p className="mt-3 text-[12px] text-paper-dim">
            Denied before pricing. No order, no token, no call to Razorpay.
          </p>
        ) : (
          <p className="mt-3 text-[12px] text-paper-dim">
            The agent&apos;s arithmetic matched. The charge is still the
            gate&apos;s figure.
          </p>
        )}
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto">
        {verdict === null || verdict.rules.length === 0 ? (
          <p className="px-4 py-4 text-[12px] text-paper-faint">
            Rules appear here as they are evaluated.
          </p>
        ) : (
          <table className="w-full border-collapse text-[12px]">
            <thead className="sticky top-0 bg-ink-raised">
              <tr className="border-b border-rule">
                <th className="eyebrow px-4 py-2 text-left font-normal">
                  Rule
                </th>
                <th className="eyebrow px-2 py-2 text-right font-normal">
                  Observed
                </th>
                <th className="eyebrow px-2 py-2 text-right font-normal">
                  Limit
                </th>
                <th className="eyebrow px-4 py-2 text-right font-normal">·</th>
              </tr>
            </thead>
            <tbody>
              {/* Failures first. A judge should not have to scroll to find the
                  rule that stopped the money. */}
              {[...verdict.rules]
                .sort((a, b) => Number(a.passed) - Number(b.passed))
                .map((r) => (
                  <tr
                    key={r.rule_id}
                    className={`border-b border-rule/50 ${r.passed ? "" : "bg-vermilion/[0.07]"}`}
                  >
                    <td
                      className={`figures px-4 py-2 ${r.passed ? "text-paper-dim" : "text-vermilion"}`}
                    >
                      {r.rule_id}
                    </td>
                    <td className="figures px-2 py-2 text-right text-paper">
                      {r.observed.toLocaleString("en-IN")}
                    </td>
                    <td className="figures px-2 py-2 text-right text-paper-faint">
                      {r.limit.toLocaleString("en-IN")}
                    </td>
                    <td
                      className={`px-4 py-2 text-right font-mono ${
                        r.passed ? "text-verdigris" : "text-vermilion"
                      }`}
                    >
                      {r.passed ? "pass" : "fail"}
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        )}
      </div>
    </section>
  );
}
